version: '3.8'

services:
  app:
    build: .
    container_name: eco-forum-manager
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - eco-software-architecture-network

networks:
  eco-software-architecture-network:
